#####################################################
#              Decade Collections                   #
#####################################################

collections:
  Best of 1970s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=1970-01-01,1979-12-31&num_votes=1000,&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213584
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1970
    sync_mode: sync
    collection_order: custom

  Best of 1980s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=1980-01-01,1989-12-31&num_votes=1000,&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213585
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1980
    sync_mode: sync
    collection_order: custom

  Best of 1990s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=1990-01-01,1999-12-31&num_votes=5000,&languages=en&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213586
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1990
    sync_mode: sync
    collection_order: custom

  Best of 2000s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=2000-01-01,2009-12-31&num_votes=5000,&languages=en&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213587
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2000
    sync_mode: sync
    collection_order: custom

  Best of 2010s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=2010-01-01,2019-12-31&num_votes=5000,&languages=en&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213588
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2010
    sync_mode: sync
    collection_order: custom

  Best of 2020s:
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=tv_series&release_date=2020-01-01,2029-12-31&num_votes=5000,&languages=en&sort=user_rating,desc
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213589
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2020
    sync_mode: sync
    collection_order: custom