##############################################################
##               Movie Awards Collections                   ##
##                Created by JJJonesJr33                    ##
##                      Version 2.0                         ##
##############################################################
##############################################################
##                                                          ##
##            User/Config Credits - Special Thanks          ##
##                                                          ##
##               Yozora, Bullmoose20, & Sohjiro             ##
##   Glasti1, Hiren-Z, OhMyBahGosh, tuxpeople, cpt-kuesel   ##
##      meisnate12, TheUnchainedZebra, Evil Tacctician      ##
##                                                          ##
##############################################################

#######################
##     Templates     ##
#######################


templates:
    Awards:
      sort_title: +01_2<<collection_name>>
      url_poster: https://theposterdb.com/api/assets/<<poster>>
    # visible_home: range(11/01-02/28)
    # visible_shared: range(11/01-02/28)
    # schedule: range(11/01-02/28)
      collection_mode: hide
      collection_order: release.desc
      sync_mode: sync
        
#############################
##       Collections       ##
#############################

collections:

  Award Winning Movies:
    template: {name: Awards, poster: 213569}
    trakt_list: 
      - https://trakt.tv/users/movistapp/lists/christmas-movies
    summary: "A collection of winning movies from the Emmys, Oscars and Golden Globe award ceremonies over the years"
