#####################################################
#              Decade Collections                   #
#####################################################

collections:
  Best of 1970s:
    trakt_list:
      - https://trakt.tv/lists/9356214
      - https://trakt.tv/lists/11571450
      - https://trakt.tv/lists/20694163
      limit: 150
    url_poster: https://theposterdb.com/api/assets/213584
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1970
    sync_mode: sync
    collection_order: custom
    schedule: daily

  Best of 1980s:
    trakt_list:
      - https://trakt.tv/lists/25573666
      - https://trakt.tv/lists/9356204
    url_poster: https://theposterdb.com/api/assets/213585
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1980
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 1990s:
    trakt_list:
      - https://trakt.tv/lists/25573648
      - https://trakt.tv/lists/23049891
    url_poster: https://theposterdb.com/api/assets/213586
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1990
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2000s:
    trakt_list:
      - https://trakt.tv/lists/23219215
      - https://trakt.tv/lists/24136798
      - https://trakt.tv/lists/25573671
    url_poster: https://theposterdb.com/api/assets/213587
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2000
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2010s:
    trakt_list:
      - https://trakt.tv/lists/23219486
      - https://trakt.tv/lists/25573637
      - https://trakt.tv/lists/22341493
    url_poster: https://theposterdb.com/api/assets/213588
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2010
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2020s:
    trakt_list:
      - https://trakt.tv/lists/23219227
      - https://trakt.tv/lists/23994046
    url_poster: https://theposterdb.com/api/assets/213589
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2020
    sync_mode: sync
    collection_order: release.desc
    schedule: daily
