#####################################################
#              Decade Collections                   #
#####################################################

collections:
  Best of 1970s:
    trakt_list:
      - https://trakt.tv/users/flipmodeg/lists/1970s
      - https://trakt.tv/users/xluquin/lists/1970s?
      - https://trakt.tv/users/rjchignell/lists/best-of-the-1970-s
    url_poster: https://theposterdb.com/api/assets/213584
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1970
    sync_mode: sync
    collection_order: custom
    schedule: daily

  Best of 1980s:
    trakt_list:
      - https://trakt.tv/users/deniax/lists/best-of-1980-1989
      - https://trakt.tv/users/flipmodeg/lists/1980s
    url_poster: https://theposterdb.com/api/assets/213585
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1980
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 1990s:
    trakt_list:
      - https://trakt.tv/users/deniax/lists/best-of-1990-1999
      - https://trakt.tv/users/jvanbortel/lists/best-of-the-1990s
    url_poster: https://theposterdb.com/api/assets/213586
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best1990
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2000s:
    trakt_list:
      - https://trakt.tv/users/mmagtech/lists/best-of-2000-2009
      - https://trakt.tv/users/perral/lists/best-of-2000s
      - https://trakt.tv/users/deniax/lists/best-of-2000-2009
    url_poster: https://theposterdb.com/api/assets/213587
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2000
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2010s:
    trakt_list:
      - https://trakt.tv/users/mmagtech/lists/best-of-2010-2019-479ab183-57ad-4943-9c03-571e50eb5082
      - https://trakt.tv/users/deniax/lists/best-of-2010-2019
      - https://trakt.tv/users/sparx710/lists/best-of-2010-2019
    url_poster: https://theposterdb.com/api/assets/213588
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2010
    sync_mode: sync
    collection_order: release.desc
    schedule: daily

  Best of 2020s:
    trakt_list:
      - https://trakt.tv/users/mmagtech/lists/best-of-2020-2030
      - https://trakt.tv/users/ofir12/lists/best-of-2020
    url_poster: https://theposterdb.com/api/assets/213589
    url_background: https://wallpapercave.com/wp/wp4016022.jpg
    sort_title: +07_Best2020
    sync_mode: sync
    collection_order: release.desc
    schedule: daily
